"""
GRA-formatted tax report generation for BizPulse AI compliance-svc.

Renders VAT returns, CIT returns, and tax invoices as HTML and converts
to PDF bytes via weasyprint.  All monetary values arrive in pesewas
(minor units) and are formatted to Ghana Cedis (GHS) for display.

SSRF mitigation (MF-4): every weasyprint call uses a url_fetcher that
returns an empty payload so external resources can never be loaded.
"""

from __future__ import annotations

import html
from datetime import datetime
from typing import Any

try:
    import weasyprint
except ImportError:
    weasyprint = None  # PDF generation unavailable without system deps

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SAFE_URL_FETCHER = lambda url, **kwargs: {  # noqa: E731
    "string": b"",
    "mime_type": "text/plain",
}
"""Block all external resource loads to prevent SSRF (MF-4)."""


def format_pesewas(amount: int) -> str:
    """Convert pesewas integer to display string ``GHS 1,234.56``.

    Negative amounts are rendered as ``-GHS 1,234.56``.
    """
    if amount < 0:
        return f"-GHS {abs(amount) / 100:,.2f}"
    return f"GHS {amount / 100:,.2f}"


def _esc(value: Any) -> str:
    """HTML-escape a value for safe template interpolation."""
    if value is None:
        return ""
    return html.escape(str(value))


def _format_date(d: Any) -> str:
    """Return a human-friendly date string from date/datetime/str."""
    if d is None:
        return ""
    if isinstance(d, datetime):
        return d.strftime("%d %b %Y")
    # date or str
    try:
        return d.strftime("%d %b %Y")
    except AttributeError:
        return _esc(str(d))


# ---------------------------------------------------------------------------
# Shared CSS
# ---------------------------------------------------------------------------

_BASE_CSS = """\
@page {
    size: A4;
    margin: 20mm 15mm 25mm 15mm;
}
body {
    font-family: sans-serif;
    font-size: 11pt;
    color: #333;
    line-height: 1.4;
    margin: 0;
    padding: 0;
}
h1, h2, h3 {
    color: #1B4332;
    margin-top: 0;
}
h1 {
    font-size: 18pt;
    border-bottom: 3px solid #1B4332;
    padding-bottom: 6px;
    margin-bottom: 16px;
}
h2 {
    font-size: 14pt;
    margin-bottom: 10px;
}
h3 {
    font-size: 12pt;
    margin-bottom: 8px;
}
table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 16px;
}
th, td {
    border: 1px solid #bbb;
    padding: 6px 10px;
    text-align: left;
    font-size: 10pt;
}
th {
    background-color: #1B4332;
    color: #fff;
    font-weight: 600;
}
td.amount {
    text-align: right;
    font-variant-numeric: tabular-nums;
}
tr.total td {
    font-weight: 700;
    border-top: 2px solid #1B4332;
}
.header-block {
    margin-bottom: 20px;
}
.header-block p {
    margin: 2px 0;
    font-size: 10pt;
}
.meta-table {
    width: auto;
    margin-bottom: 16px;
}
.meta-table td {
    border: none;
    padding: 2px 12px 2px 0;
    font-size: 10pt;
}
.meta-table td.label {
    font-weight: 600;
    color: #1B4332;
    white-space: nowrap;
}
.note {
    font-size: 9pt;
    color: #555;
    margin-top: 20px;
    border-top: 1px solid #ccc;
    padding-top: 8px;
}
.footer {
    font-size: 8pt;
    color: #888;
    text-align: center;
    margin-top: 30px;
    border-top: 1px solid #ddd;
    padding-top: 6px;
}
"""

_FOOTER_HTML = """\
<div class="footer">
    BizPulse AI &mdash; Compliance Report
</div>
"""

_GENERAL_NOTE = (
    "Generated by BizPulse AI. Amounts in Ghana Cedis (GHS). "
    "All computations derived from transaction records."
)

# ---------------------------------------------------------------------------
# VAT Report
# ---------------------------------------------------------------------------


def render_vat_report_pdf(report: dict) -> bytes:
    """Render a GRA VAT Return as a PDF.

    Parameters
    ----------
    report:
        Dictionary matching the shape of
        :class:`models.VATReportResponse`.

    Returns
    -------
    bytes
        PDF file content.
    """
    business_name = _esc(report.get("business_name", ""))
    business_tin = _esc(report.get("business_tin", "N/A"))
    period_start = _format_date(report.get("period_start"))
    period_end = _format_date(report.get("period_end"))
    period_id = _esc(report.get("period_id", ""))
    computation_date = _format_date(report.get("computation_date"))

    taxable_sales = report.get("taxable_sales_pesewas", 0)
    output_vat = report.get("output_vat_pesewas", 0)
    taxable_purchases = report.get("taxable_purchases_pesewas", 0)
    input_vat = report.get("input_vat_pesewas", 0)
    net_vat = report.get("net_vat_payable_pesewas", 0)
    nhil = report.get("nhil_pesewas", 0)
    getfund = report.get("getfund_pesewas", 0)
    total_payable = report.get("total_payable_pesewas", 0)

    html_content = f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><style>{_BASE_CSS}</style></head>
<body>
<h1>VAT / NHIL / GETFund Return</h1>

<div class="header-block">
    <table class="meta-table">
        <tr><td class="label">Business Name:</td><td>{business_name}</td></tr>
        <tr><td class="label">TIN:</td><td>{business_tin}</td></tr>
        <tr><td class="label">Period:</td><td>{period_start} &ndash; {period_end}</td></tr>
        <tr><td class="label">Period ID:</td><td>{period_id}</td></tr>
        <tr><td class="label">Computation Date:</td><td>{computation_date}</td></tr>
    </table>
</div>

<h2>Output Tax (Sales)</h2>
<table>
    <thead>
        <tr><th>Description</th><th style="width:35%">Amount</th></tr>
    </thead>
    <tbody>
        <tr>
            <td>Total Taxable Sales</td>
            <td class="amount">{format_pesewas(taxable_sales)}</td>
        </tr>
        <tr>
            <td>Output VAT</td>
            <td class="amount">{format_pesewas(output_vat)}</td>
        </tr>
    </tbody>
</table>

<h2>Input Tax (Purchases)</h2>
<table>
    <thead>
        <tr><th>Description</th><th style="width:35%">Amount</th></tr>
    </thead>
    <tbody>
        <tr>
            <td>Total Taxable Purchases</td>
            <td class="amount">{format_pesewas(taxable_purchases)}</td>
        </tr>
        <tr>
            <td>Input VAT</td>
            <td class="amount">{format_pesewas(input_vat)}</td>
        </tr>
    </tbody>
</table>

<h2>Tax Payable Summary</h2>
<table>
    <thead>
        <tr><th>Component</th><th style="width:35%">Amount</th></tr>
    </thead>
    <tbody>
        <tr>
            <td>Net VAT Payable (Output VAT &minus; Input VAT)</td>
            <td class="amount">{format_pesewas(net_vat)}</td>
        </tr>
        <tr>
            <td>NHIL (National Health Insurance Levy)</td>
            <td class="amount">{format_pesewas(nhil)}</td>
        </tr>
        <tr>
            <td>GETFund Levy</td>
            <td class="amount">{format_pesewas(getfund)}</td>
        </tr>
        <tr class="total">
            <td>Total Amount Payable</td>
            <td class="amount">{format_pesewas(total_payable)}</td>
        </tr>
    </tbody>
</table>

<div class="note">
    <p><strong>Note:</strong> Input VAT is estimated based on standard-rated
    expense transactions. Actual input VAT may differ.</p>
    <p>{_esc(_GENERAL_NOTE)}</p>
</div>

{_FOOTER_HTML}
</body>
</html>
"""
    pdf_doc = weasyprint.HTML(string=html_content, url_fetcher=_SAFE_URL_FETCHER)
    return pdf_doc.write_pdf()


# ---------------------------------------------------------------------------
# CIT Report
# ---------------------------------------------------------------------------


def render_cit_report_pdf(report: dict) -> bytes:
    """Render a GRA Corporate Income Tax (CIT) Return as a PDF.

    Parameters
    ----------
    report:
        Dictionary matching the shape of
        :class:`models.CITReportResponse`.

    Returns
    -------
    bytes
        PDF file content.
    """
    business_name = _esc(report.get("business_name", ""))
    business_tin = _esc(report.get("business_tin", "N/A"))
    period_start = _format_date(report.get("period_start"))
    period_end = _format_date(report.get("period_end"))
    period_id = _esc(report.get("period_id", ""))
    computation_date = _format_date(report.get("computation_date"))

    revenue = report.get("total_revenue_pesewas", 0)
    deductible = report.get("total_deductible_expenses_pesewas", 0)
    non_deductible = report.get("non_deductible_expenses_pesewas", 0)
    net_profit = report.get("net_profit_pesewas", 0)
    cit_rate_bps = report.get("cit_rate_bps", 0)
    cit_liability = report.get("cit_liability_pesewas", 0)

    # Display rate: bps -> percentage (e.g. 2500 -> 25.00%)
    cit_rate_pct = f"{cit_rate_bps / 100:.2f}%"

    html_content = f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><style>{_BASE_CSS}</style></head>
<body>
<h1>Corporate Income Tax Return</h1>

<div class="header-block">
    <table class="meta-table">
        <tr><td class="label">Business Name:</td><td>{business_name}</td></tr>
        <tr><td class="label">TIN:</td><td>{business_tin}</td></tr>
        <tr><td class="label">Period:</td><td>{period_start} &ndash; {period_end}</td></tr>
        <tr><td class="label">Period ID:</td><td>{period_id}</td></tr>
        <tr><td class="label">Computation Date:</td><td>{computation_date}</td></tr>
    </table>
</div>

<h2>Income Statement Summary</h2>
<table>
    <thead>
        <tr><th>Item</th><th style="width:35%">Amount</th></tr>
    </thead>
    <tbody>
        <tr>
            <td>Total Revenue</td>
            <td class="amount">{format_pesewas(revenue)}</td>
        </tr>
        <tr>
            <td>Less: Total Deductible Expenses</td>
            <td class="amount">({format_pesewas(deductible)})</td>
        </tr>
        <tr>
            <td>Non-Deductible Expenses (for reference)</td>
            <td class="amount">{format_pesewas(non_deductible)}</td>
        </tr>
        <tr class="total">
            <td>Net Profit / (Loss)</td>
            <td class="amount">{format_pesewas(net_profit)}</td>
        </tr>
    </tbody>
</table>

<h2>Tax Computation</h2>
<table>
    <thead>
        <tr><th>Description</th><th style="width:35%">Value</th></tr>
    </thead>
    <tbody>
        <tr>
            <td>Chargeable Income</td>
            <td class="amount">{format_pesewas(net_profit)}</td>
        </tr>
        <tr>
            <td>CIT Rate</td>
            <td class="amount">{cit_rate_pct}</td>
        </tr>
        <tr class="total">
            <td>Corporate Income Tax Liability</td>
            <td class="amount">{format_pesewas(cit_liability)}</td>
        </tr>
    </tbody>
</table>

<div class="note">
    <p>{_esc(_GENERAL_NOTE)}</p>
</div>

{_FOOTER_HTML}
</body>
</html>
"""
    pdf_doc = weasyprint.HTML(string=html_content, url_fetcher=_SAFE_URL_FETCHER)
    return pdf_doc.write_pdf()


# ---------------------------------------------------------------------------
# Invoice
# ---------------------------------------------------------------------------


def render_invoice_pdf(
    business: dict,
    request_data: dict,
    vat_rate_bps: int,
) -> bytes:
    """Render a tax invoice as a PDF.

    Parameters
    ----------
    business:
        Business details with keys ``legal_name``, ``trading_name``,
        ``tax_identification_number``, ``country_code``.
    request_data:
        Invoice data with keys ``customer_name``, ``customer_tin``
        (optional), ``line_items`` (list of dicts with ``description``,
        ``quantity``, ``unit_price_pesewas``, ``vat_applicable``),
        and ``notes`` (optional).
    vat_rate_bps:
        VAT rate in basis points (e.g. 1500 = 15.00%).

    Returns
    -------
    bytes
        PDF file content.
    """
    legal_name = _esc(business.get("legal_name", ""))
    trading_name = _esc(business.get("trading_name", ""))
    seller_tin = _esc(business.get("tax_identification_number", "N/A"))
    country_code = _esc(business.get("country_code", "GH"))

    customer_name = _esc(request_data.get("customer_name", ""))
    customer_tin = _esc(request_data.get("customer_tin") or "")
    notes = _esc(request_data.get("notes") or "")
    line_items = request_data.get("line_items", [])

    vat_rate_pct = vat_rate_bps / 100  # e.g. 15.00
    invoice_date = datetime.utcnow().strftime("%d %b %Y")

    # Build line-item rows and running totals
    subtotal_pesewas = 0
    total_vat_pesewas = 0
    rows_html = ""

    for idx, item in enumerate(line_items, start=1):
        desc = _esc(item.get("description", ""))
        qty = item.get("quantity", 1.0)
        unit_price = item.get("unit_price_pesewas", 0)
        vat_applicable = item.get("vat_applicable", True)

        line_subtotal = int(qty * unit_price)
        if vat_applicable:
            line_vat = int(round(line_subtotal * vat_rate_bps / 10_000))
        else:
            line_vat = 0
        line_total = line_subtotal + line_vat

        subtotal_pesewas += line_subtotal
        total_vat_pesewas += line_vat

        vat_label = format_pesewas(line_vat) if vat_applicable else "Exempt"

        rows_html += f"""\
        <tr>
            <td style="text-align:center">{idx}</td>
            <td>{desc}</td>
            <td style="text-align:center">{qty:g}</td>
            <td class="amount">{format_pesewas(unit_price)}</td>
            <td class="amount">{format_pesewas(line_subtotal)}</td>
            <td class="amount">{vat_label}</td>
            <td class="amount">{format_pesewas(line_total)}</td>
        </tr>
"""

    grand_total_pesewas = subtotal_pesewas + total_vat_pesewas

    customer_tin_row = ""
    if customer_tin:
        customer_tin_row = (
            f'<tr><td class="label">Customer TIN:</td>'
            f"<td>{customer_tin}</td></tr>"
        )

    notes_section = ""
    if notes:
        notes_section = f"""\
<h3>Notes</h3>
<p style="font-size:10pt;color:#555">{notes}</p>
"""

    display_name = trading_name if trading_name else legal_name

    html_content = f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><style>{_BASE_CSS}
.invoice-header {{
    display: flex;
    justify-content: space-between;
    margin-bottom: 20px;
}}
.invoice-header .seller {{
    flex: 1;
}}
.invoice-header .title {{
    text-align: right;
    flex: 1;
}}
.invoice-header .title h1 {{
    border-bottom: none;
    margin-bottom: 4px;
}}
</style></head>
<body>

<table style="width:100%;border:none;margin-bottom:20px">
    <tr style="border:none">
        <td style="border:none;vertical-align:top;width:60%">
            <h2 style="margin-bottom:4px">{display_name}</h2>
            <p style="font-size:10pt;margin:2px 0;color:#555">{legal_name}</p>
            <p style="font-size:10pt;margin:2px 0">TIN: {seller_tin}</p>
            <p style="font-size:10pt;margin:2px 0">Country: {country_code}</p>
        </td>
        <td style="border:none;vertical-align:top;text-align:right">
            <h1 style="border-bottom:none;text-align:right">TAX INVOICE</h1>
            <p style="font-size:10pt;margin:2px 0">Date: {invoice_date}</p>
        </td>
    </tr>
</table>

<div class="header-block">
    <h3>Bill To</h3>
    <table class="meta-table">
        <tr><td class="label">Customer:</td><td>{customer_name}</td></tr>
        {customer_tin_row}
    </table>
</div>

<h2>Line Items</h2>
<table>
    <thead>
        <tr>
            <th style="width:5%;text-align:center">#</th>
            <th>Description</th>
            <th style="width:8%;text-align:center">Qty</th>
            <th style="width:14%">Unit Price</th>
            <th style="width:14%">Subtotal</th>
            <th style="width:14%">VAT ({vat_rate_pct:g}%)</th>
            <th style="width:14%">Total</th>
        </tr>
    </thead>
    <tbody>
{rows_html}\
    </tbody>
</table>

<table style="width:50%;margin-left:auto;margin-bottom:20px">
    <tbody>
        <tr>
            <td style="font-weight:600;border:none;text-align:right;padding-right:16px">Subtotal:</td>
            <td class="amount" style="border:none">{format_pesewas(subtotal_pesewas)}</td>
        </tr>
        <tr>
            <td style="font-weight:600;border:none;text-align:right;padding-right:16px">VAT ({vat_rate_pct:g}%):</td>
            <td class="amount" style="border:none">{format_pesewas(total_vat_pesewas)}</td>
        </tr>
        <tr class="total">
            <td style="font-weight:700;border:none;border-top:2px solid #1B4332;text-align:right;padding-right:16px">Grand Total:</td>
            <td class="amount" style="border:none;border-top:2px solid #1B4332">{format_pesewas(grand_total_pesewas)}</td>
        </tr>
    </tbody>
</table>

{notes_section}

<div class="note">
    <p>{_esc(_GENERAL_NOTE)}</p>
</div>

{_FOOTER_HTML}
</body>
</html>
"""
    pdf_doc = weasyprint.HTML(string=html_content, url_fetcher=_SAFE_URL_FETCHER)
    return pdf_doc.write_pdf()
